//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class BacktestingBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BacktestingBatch()
        {
            this.Backtestings = new HashSet<Backtesting>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int StrategyId { get; set; }
        public int TemporalityId { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Backtesting> Backtestings { get; set; }
        public virtual Strategy Strategy { get; set; }
        public virtual Temporality Temporality { get; set; }
    }
}
