//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndicatorConfiguration
    {
        public int Id { get; set; }
        public int IndicatorId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public Nullable<int> DataTypeId { get; set; }
    
        public virtual IndicatorMetaDataType IndicatorMetaDataType { get; set; }
        public virtual Indicator Indicator { get; set; }
    }
}
