//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temporality
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Temporality()
        {
            this.BacktestingBatches = new HashSet<BacktestingBatch>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int CryptoPairId { get; set; }
        public int Minutes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BacktestingBatch> BacktestingBatches { get; set; }
        public virtual CryptoPair CryptoPair { get; set; }
    }
}
